FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install -y \
    libasound2-dev:arm64 \
    libudev-dev:arm64 \
    libwayland-dev:arm64 \
    libxkbcommon-dev:arm64 \
    pkg-config

ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
