//! LAN Discovery domain model — cross-network-agnostic room representation.
//!
//! `RoomMetadata` contains **zero** network/transport information (no IP, port,
//! relay, or protocol details). It can be serialized and reused across LAN
//! (UDP beacon), public lobby (HTTP JSON), or Steam lobby unchanged.
//!
//! See `docs/architecture/discovery-model.md` for design rationale.

use serde::{Deserialize, Serialize};

/// Unique room identifier. Generated by the room creator (SessionHost).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RoomId(pub u64);

/// Unique relay instance identifier. Changes when a relay restarts,
/// even if the same `RoomId` is reused (e.g., host crash + recreate).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RelayId(pub u64);

/// Room lifecycle state. `Starting` is reserved for future countdown/loading phase.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum RoomState {
    Waiting,
    Starting,
    Playing,
}

/// Pure room metadata — zero network information.
///
/// This struct is the single source of truth for what a "room" is.
/// It contains only logical room properties and is independent of
/// how the room is discovered (UDP, HTTP, Steam, etc.).
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoomMetadata {
    pub room_id: RoomId,
    /// Human-readable room name. Auto-generated if empty (future #10 may add input).
    pub room_name: String,
    /// Map identifier string, e.g. "grassland_small", "desert_01".
    /// Uses String, not enum, to support future Workshop/Mod maps without protocol change.
    pub map_id: String,
    pub current_players: u8,
    pub max_players: u8,
    pub state: RoomState,
}

/// Discovery-layer advertisement: room metadata + connection info.
///
/// This is the struct that gets serialized and transmitted over the LAN discovery
/// protocol. It adds transport-layer fields (`relay_id`, `endpoint`) to the
/// network-agnostic `RoomMetadata`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoomAdvertisement {
    pub relay_id: RelayId,
    /// TCP endpoint for connecting to the relay (IP:port).
    pub endpoint: String,
    pub room: RoomMetadata,
}
